name: C/C++ CI

on:
  push:
    branches: [ dev ]

jobs:
  install:
    
    runs-on: ubuntu-20.04

    steps:
      - name: install packages
        run: sudo apt install libboost-dev libboost-program-options-dev libgtest-dev libfmt-dev gcc-10 g++-10 clang-10 ninja-build cmake
      - name: build gtest
        run: sudo mkdir /usr/src/googletest/googletest/build && cd /usr/src/googletest/googletest/build && sudo cmake .. && sudo make install -j10
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: pwd && mkdir build && cd build && CXX=/usr/bin/clang++-10 CC=/usr/bin/clang-10 cmake -DCMAKE_BUILD_TYPE=Debug ..
    - name: build
      run: cmake --build . -- -j10
    - name: run test
      run: ./webpptest
